name: CI

on: [push]

env:
  PYTHON_VERSION: '3.11'

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Run pytest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync

    - name: Run pytest
      run: |
        uv run pytest test/

  mypy:
    runs-on: ubuntu-latest
    name: Run mypy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync

    - name: Run mypy
      run: |
        uv run mypy .

  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit checks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync

    - name: Run pre-commit checks
      run: |
        uv run pre-commit run --all-files
