name: Publish to PyPI

on:
  release:
    types: [created]

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Build wheel
      run: |
        poetry build -vv --no-interaction

    - name: Get wheel filename
      id: wheel_filename
      run: |
        echo "file_path=$(ls dist/*.whl)" >> $GITHUB_OUTPUT
        echo "file_name=$(ls dist/*.whl) | xargs -n 1 basename" >> $GITHUB_OUTPUT

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Upload wheel as release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.wheel_filename.outputs.file_path }}
        asset_name: ${{ steps.wheel_filename.outputs.file_name }}
        asset_content_type: application/zip
